# Generated by Django 6.0.6 on 2026-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lastname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('github', models.CharField(blank=True, max_length=600, null=True, verbose_name='لینک گیتهاب')),
                ('site', models.CharField(blank=True, max_length=600, null=True, verbose_name='لینک سایت')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('site_des', models.TextField(verbose_name='توضیحات')),
                ('github_link', models.URLField(verbose_name='یو آر ال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
            ],
        ),
    ]
